### ISSUE TITLE
Input issue with very old DJ DAO IIDX controllers (pre-2012)

### ISSUE THREAD

**Issue by sp2xdev** [spice2x/spice2x.github.io#78]
Occasionally people complain that DJ DAO IIDX controllers from **before** 2012 do not work with spice.

For timeline:

* Very old Dao controllers (FP7 etc) = made before 2012, firmware not updatable, green PCB, has daughterboard for turntable, has issues with some buttons or turntables with spice
* Old Dao controllers (FPS, FP7, PEE, etc) = sometimes known as "2012 edition", black PCB with updatable FW, no daughterboard, no reported issues with spice (has been tested extensively)
* New Dao controllers: Phoenixwan, FPS Gen2 - of course, work nicely with spice

No clue what the actual issue is, probably some odd PS2 compatibility thing, or bad USB-HID code again.

(To note, spice has an erratum fix for DAO controllers made after 2012, before Phoenixwan)

**Comment by AllanCat** [comment]
For green PCB version it is due to PS2 compatibility, which button 7 will also affect turntable.
The workaround right now is by manually edit input config as following:
C:\Users\{UserName}\AppData\Roaming\spicetools.xml
name="P1 7" vkey="4" analogtype="2"
name="P1 TT+" vkey="3" analogtype="2"
name="P1 TT-" vkey="3" analogtype="3"
