### ISSUE TITLE
Add explanation on how overlay hotkeys work

### ISSUE THREAD

**Issue by sp2xdev** [spice2x/spice2x.github.io#79]
There's no documentation available (or any UI hints) on how Hotkey Enable 1/2 and Hotkey Toggle work.... probably needs some help text in the configurator UI.

**Comment by LupinThidr** [comment]
There's practically zero documentation about the overlay at all, other than what's available on the spicetools announcement threads. The default bindings were included in the README at some point.
(actually, there's hardly any public info about the various spicetools/spice2x features beyond the changelogs, but maybe that's intentional)

Here are my suggestions:

* list default bindings / overlay details on the spice2x github.io page, and whatever else was included in the original spicetools posts (without game screenshots). for example, if someone were to upgrade from spicetools to spice2x they'd have no idea about the ticker feature without digging through the changelog.
* dedicated overlay tab, right now the overlay bindings are at the very bottom of the game tab
