### ISSUE TITLE
SDVX VM subscreen doesn't work for SpiceCompanion Android

### ISSUE THREAD

**Issue by sp2xdev** [spice2x/spice2x.github.io#94]
It works for iOS app, but not for Android. The Android app was never updated after EG came out.

Don't have access to the app's source code, but maybe something can be done on the server side to trick the app into working.

**Comment by LupinThidr** [comment]
I've created a repo with the last release (2021-02-28) source code with a few unpublished commits at https://github.com/LupinThidr/spicecompanion
Android apk + source tarball is available at the usual site (spicecompanion-latest rather than spicetools-latest), but I've uploaded it as a GitHub release: https://github.com/LupinThidr/spicecompanion/releases/tag/1.2.4%2B26
